
import { Transaction, TransactionCategory, TransactionType, User } from './types';

export const CURRENT_USER: User = {
  id: 'u123',
  name: 'Jenifer Jackson',
  accountNumber: '•••• 4582',
  balance: 438762.09,
  monthlyIncome: 8200.00,
  monthlyExpense: 3450.20,
  accountStatus: 'On Hold',
  dueCharges: 600.00,
};

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx_1',
    date: '2023-10-24T14:30:00',
    merchant: 'Whole Foods Market',
    amount: 142.50,
    type: TransactionType.DEBIT,
    category: TransactionCategory.FOOD,
    status: 'Completed',
    location: 'San Francisco, CA',
    cardLast4: '4582',
    note: 'Weekly groceries',
  },
  {
    id: 'tx_2',
    date: '2023-10-23T09:15:00',
    merchant: 'Uber Technologies',
    amount: 24.90,
    type: TransactionType.DEBIT,
    category: TransactionCategory.TRANSPORT,
    status: 'Completed',
    location: 'San Francisco, CA',
    cardLast4: '4582',
    note: 'Ride to airport',
  },
  {
    id: 'tx_3',
    date: '2023-10-22T18:00:00',
    merchant: 'TechStyle Inc.',
    amount: 3500.00,
    type: TransactionType.CREDIT,
    category: TransactionCategory.INCOME,
    status: 'Completed',
    location: 'Direct Deposit',
    note: 'Consulting payment',
    referenceNumber: 'ACH-882190-X',
  },
  {
    id: 'tx_4',
    date: '2023-10-21T20:45:00',
    merchant: 'Netflix Subscription',
    amount: 15.99,
    type: TransactionType.DEBIT,
    category: TransactionCategory.ENTERTAINMENT,
    status: 'Pending',
    cardLast4: '4582',
  },
  {
    id: 'tx_5',
    date: '2023-10-20T12:30:00',
    merchant: 'Starbucks Coffee',
    amount: 6.45,
    type: TransactionType.DEBIT,
    category: TransactionCategory.FOOD,
    status: 'Completed',
    location: 'San Francisco, CA',
    cardLast4: '4582',
  },
  {
    id: 'tx_6',
    date: '2023-10-19T15:20:00',
    merchant: 'Apple Store',
    amount: 1299.00,
    type: TransactionType.DEBIT,
    category: TransactionCategory.SHOPPING,
    status: 'Completed',
    location: 'Online Store',
    cardLast4: '4582',
    note: 'New iPad Pro',
  },
  {
    id: 'tx_7',
    date: '2023-10-18T08:00:00',
    merchant: 'Electric Company',
    amount: 145.20,
    type: TransactionType.DEBIT,
    category: TransactionCategory.UTILITIES,
    status: 'Failed',
    note: 'Failed due to incorrect account details',
    referenceNumber: 'ACH-ERR-991',
  },
];

export const SPENDING_DATA = [
  { name: 'Mon', amount: 120 },
  { name: 'Tue', amount: 450 },
  { name: 'Wed', amount: 200 },
  { name: 'Thu', amount: 800 },
  { name: 'Fri', amount: 1400 },
  { name: 'Sat', amount: 600 },
  { name: 'Sun', amount: 300 },
];
